# 1. Create a 3x3x3 array with random values 

In [45]:
import numpy as np
a=[[np.random.randint(3,10) for i in range(3)]for j in range(3)]
a=np.array(a).reshape(3,3,1)
print(a)

[[[9]
  [8]
  [8]]

 [[8]
  [9]
  [3]]

 [[5]
  [8]
  [9]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
arr=[[0 for i in range(5)]for j in range(5)]
c=1
for i in range(5):
    for j in range(5):
        if j==(i-1):
            arr[i][j]=c
            c+=1
        if i==j:
            break
arr=np.array(arr)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
# 1-> white
# 0-> black
arr1=[[0 for i in range(8)]for j in range(8)]
c=1
for i in range(8):
    for j in range(8):
        if not(c)==False:
            arr1[i][j]=0
        else:
            arr1[i][j]=1
        c=not(c)
    c=not(c)
arr1=np.array(arr1)
print(arr1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
a=[[0 for i in range(5)] for j in range(5)]
for i in range(5):
    for j in range(5):
        a[i][j]=np.random.randint(3,20)
a=np.array(a)
print(a,"\n")
a=a-a.mean()
a=a/a.max()
print(a)

[[13  7 12 14  8]
 [ 7  8 14 14 15]
 [ 8  3 12 18  6]
 [18  6 10 11 14]
 [19 17 13 11 10]] 

[[ 0.19786096 -0.60427807  0.06417112  0.3315508  -0.47058824]
 [-0.60427807 -0.47058824  0.3315508   0.3315508   0.46524064]
 [-0.47058824 -1.13903743  0.06417112  0.86631016 -0.73796791]
 [ 0.86631016 -0.73796791 -0.20320856 -0.06951872  0.3315508 ]
 [ 1.          0.73262032  0.19786096 -0.06951872 -0.20320856]]


# 5.  How to find common values between two arrays?

In [5]:
arr=np.array(list(map(int,input().split())))
arr1=np.array(list(map(int,input().split())))
print(arr)
print(arr1)
print("Common values are:")
for i in arr:
    if i in arr1:
        print(i)
    

1 46 78 9
78 5 9
[ 1 46 78  9]
[78  5  9]
Common values are:
78
9


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("Yesterday:",yesterday,"\n","Today:",today,"\n","Tomorrow:",tomorrow)

Yesterday: 2020-07-27 
 Today: 2020-07-28 
 Tomorrow: 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
A=list(map(int,input().split()))
A=np.array(A)
B=list(map(int,input().split()))
B=np.array(B)
print(A)
print(B)
equal=np.allclose(A,B)
print(equal)

4 0 1 5 6
4 0 1 5 6
[4 0 1 5 6]
[4 0 1 5 6]
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
v=np.random.randint(2,20,10)
print(v)
a=v.max()
for i in range(10):
    if v[i]==a:
        v[i]=0
print("\nAfter replacing maximum values with 0 we get:\n\n",v)

[10 19 18  9 18 10 16 12 19 16]

After replacing maximum values with 0 we get:

 [10  0 18  9 18 10 16 12  0 16]


# 9. How to print all the values of an array?

In [9]:
# For 1d
print("For 1D")
arr=np.array([1,2,3,4,5,6])
print(arr)
for i in arr:
    print(i)
# For 2d
print("\nFor 2D")
arr1=arr.reshape(6,1)
print(arr1)
for i in range(6):
    for j in range(1):
        print(arr1[i][j])
arr2=arr1.reshape(2,3,1)
# For 3d
print("\nFor 3D")
print(arr2)
for i in range(2):
    for j in range(3):
        for k in range(1):
            print(arr2[i][j][k])

For 1D
[1 2 3 4 5 6]
1
2
3
4
5
6

For 2D
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
1
2
3
4
5
6

For 3D
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
1
2
3
4
5
6


# 10.Subtract the mean of each row of a matrix

In [10]:
arr=np.random.rand(5,5)
print(arr)
print(arr.mean(axis=1,keepdims=True))
arr=arr-arr.mean(axis=1,keepdims=True)
print("\nAfter subtracting the mean of each row of a matrix:\n\n",arr)

[[ 0.1992141   0.27904934  0.70285084  0.46818148  0.7149341 ]
 [ 0.28992466  0.58106361  0.95232314  0.37210543  0.96855782]
 [ 0.85129496  0.76681086  0.9145375   0.85445713  0.98452455]
 [ 0.70663337  0.62286683  0.98831563  0.31579414  0.62873401]
 [ 0.15706251  0.60916743  0.67789865  0.66571451  0.45573222]]
[[ 0.47284597]
 [ 0.63279493]
 [ 0.874325  ]
 [ 0.65246879]
 [ 0.51311506]]

After subtracting the mean of each row of a matrix:

 [[-0.27363187 -0.19379664  0.23000487 -0.00466449  0.24208813]
 [-0.34287027 -0.05173132  0.31952821 -0.2606895   0.33576289]
 [-0.02303004 -0.10751414  0.0402125  -0.01986787  0.11019955]
 [ 0.05416457 -0.02960197  0.33584684 -0.33667466 -0.02373478]
 [-0.35605255  0.09605237  0.16478358  0.15259944 -0.05738284]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [27]:
arr1=np.random.randint(10,20,6)
print(arr1,"\n")
arr=[1,4,4,3]
arr=list(dict.fromkeys(arr))
arr=np.array(arr)
print("Second vector for indexes: ",arr,"\n")
for i in arr:
    arr1[i]+=1
print(arr1)



[18 12 10 17 13 14] 

Second vector for indexes:  [1 3 4] 

[18 13 10 18 14 14]


# 12.How to get the diagonal of a dot product?

In [41]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[10,11,12],[13,14,15],[16,17,18]])
C=np.dot(A,B)
print(C,"\n")
print("\n Diagonal of the dot product is: \n")
for i in range(3):
    for j in range(3):
        if i==j:
            print(C[i][j],end=" ")
        else:
            print(" ",end=" ")
    print("\n")

[[ 84  90  96]
 [201 216 231]
 [318 342 366]] 


 Diagonal of the dot product is: 

84     

  216   

    366 



# 13.How to find the most frequent value in an array?

In [11]:
from collections import defaultdict
d=defaultdict(lambda:0)
A=list(map(int,input().split()))
A=np.array(A)
print(A)
for i in A:
    d[i]+=1
max1=d[i]
value=i
for i,j in d.items():
    if j>max1:
        max1=j
        value=i

print("Most frequent value is: ",value)
    

1 4 4 7 6 5 5 4 4 4 
[1 4 4 7 6 5 5 4 4 4]
Most frequent value is:  4


# 14.How to get the n largest values of an array

In [12]:
n=int(input("Enter the value of n: "))
A=np.array(list(map(int,input().split())))
print(A)
A=sorted(A)
A=A[::-1]

for i in range(n):
    print(A[i])
    

Enter the value of n: 4
34 6 89 57 60 7 12 35 67
[34  6 89 57 60  7 12 35 67]
89
67
60
57


# 15.How to create a record array from a regular array?

In [20]:
arr1=np.array([("Tony",1,2.3),("Steve",2,2.3)])
print("Original array:\n\n",arr1,"\n")
rec=np.core.records.fromarrays(arr1.T,names='col1,col2',formats='S80,i8,f8')
print("Recorded array:\n\n",rec)

Original array:

 [['Tony' '1' '2.3']
 ['Steve' '2' '2.3']] 

Recorded array:

 [(b'Tony', 1,  2.3) (b'Steve', 2,  2.3)]
